server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: nabo-backend
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  pattern:
    console: "%d [%-5level] [%logger] : %msg%n"
  level:
    com.nabo: INFO
    org.springframework: ERROR

nabo:
  jwt-token-days-to-expire: ${JWT_DAYS_FOR_TOKEN_TO_EXPIRE}
  jwt-secret: ${JWT_SECRET}
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/nabo
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: none

flyway:
  url: jdbc:postgresql://localhost:5432/nabo
  schemas: nabo
  user: admin
  password: password

logging:
  level:
    com.nabo: DEBUG
    org.springframework: INFO

name: local
